apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cenotoo.fullname" . }}-cassandra-writer
  labels:
    app.kubernetes.io/component: cassandra-writer
    {{- include "cenotoo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumers.cassandraWriter.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: cassandra-writer
      {{- include "cenotoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cassandra-writer
        {{- include "cenotoo.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: cassandra-writer
          image: "{{ .Values.consumers.cassandraWriter.image.repository }}:{{ .Values.consumers.cassandraWriter.image.tag }}"
          imagePullPolicy: {{ .Values.consumers.cassandraWriter.image.pullPolicy }}
          env:
            - name: COLLECTION_NAME
              value: {{ .Values.consumers.cassandraWriter.env.collectionName | quote }}
            - name: PROJECT_NAME
              value: {{ .Values.consumers.cassandraWriter.env.projectName | quote }}
            - name: ORGANIZATION_NAME
              value: {{ .Values.consumers.cassandraWriter.env.organizationName | quote }}
            - name: KAFKA_BROKER
              value: {{ include "cenotoo.fullname" . }}-kafka-kafka-bootstrap:9092
            - name: CASSANDRA_NODES
              value: {{ include "cenotoo.fullname" . }}-cassandra-{{ .Values.cassandra.datacenterName }}-service
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenotoo.fullname" . }}-kafka-credentials
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenotoo.fullname" . }}-kafka-credentials
                  key: password
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenotoo.fullname" . }}-cassandra-superuser
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenotoo.fullname" . }}-cassandra-superuser
                  key: password
          resources:
            {{- toYaml .Values.consumers.cassandraWriter.resources | nindent 12 }}
