apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cenotoo.fullname" . }}-live-consumer
  labels:
    app.kubernetes.io/component: live-consumer
    {{- include "cenotoo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.consumers.liveConsumer.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: live-consumer
      {{- include "cenotoo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: live-consumer
        {{- include "cenotoo.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: live-consumer
          image: "{{ .Values.consumers.liveConsumer.image.repository }}:{{ .Values.consumers.liveConsumer.image.tag }}"
          imagePullPolicy: {{ .Values.consumers.liveConsumer.image.pullPolicy }}
          env:
            - name: COLLECTION_NAME
              value: {{ .Values.consumers.liveConsumer.env.collectionName | quote }}
            - name: PROJECT_NAME
              value: {{ .Values.consumers.liveConsumer.env.projectName | quote }}
            - name: ORGANIZATION_NAME
              value: {{ .Values.consumers.liveConsumer.env.organizationName | quote }}
            - name: KAFKA_BROKER
              value: {{ include "cenotoo.fullname" . }}-kafka-kafka-bootstrap:9092
            - name: KAFKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenotoo.fullname" . }}-kafka-credentials
                  key: username
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "cenotoo.fullname" . }}-kafka-credentials
                  key: password
          resources:
            {{- toYaml .Values.consumers.liveConsumer.resources | nindent 12 }}
