apiVersion: v1
kind: Service
metadata:
  name: cenotoo-coap-bridge
  labels:
    app.kubernetes.io/component: coap-bridge
    app.kubernetes.io/part-of: cenotoo
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: coap-bridge
    app.kubernetes.io/part-of: cenotoo
  ports:
    - name: coap-udp
      port: 5683
      targetPort: 5683
      protocol: UDP
      nodePort: 30683
    - name: health-http
      port: 8080
      targetPort: 8080
      protocol: TCP
