apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cenotoo.fullname" . }}-flink-data
  labels:
    {{- include "cenotoo.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.flink.storage.storageClassName }}
  storageClassName: {{ .Values.flink.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.flink.storage.size }}
