apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cenotoo-flink-data
  labels:
    app.kubernetes.io/part-of: cenotoo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
