apiVersion: v1
kind: ServiceAccount
metadata:
  name: flink
  labels:
    app.kubernetes.io/part-of: cenotoo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flink
  labels:
    app.kubernetes.io/part-of: cenotoo
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flink
  labels:
    app.kubernetes.io/part-of: cenotoo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flink
subjects:
  - kind: ServiceAccount
    name: flink
    namespace: cenotoo
