apiVersion: v1
kind: Service
metadata:
  name: cenotoo-flink-sql-gateway
  labels:
    app.kubernetes.io/part-of: cenotoo
spec:
  selector:
    component: jobmanager
    app: cenotoo-flink
  ports:
    - name: sql-gateway
      port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
