#!/usr/bin/env bash
# =============================================================================
# configure-secrets.sh — Generate Cenotoo K8s secrets from environment variables
#
# Usage:
#   export CENOTOO_ADMIN_PASSWORD=MySecurePass123
#   export CENOTOO_JWT_SECRET=$(openssl rand -hex 32)
#   export CENOTOO_POSTGRES_PASSWORD=MySecurePass123
#   ./scripts/configure-secrets.sh
#
# All variables are optional. Unset variables keep their defaults.
# Run BEFORE 07-deploy-cenotoo.sh and 24-deploy-postgres.sh
# (or re-run + kubectl apply to update).
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SECRETS_DIR="$(cd "$SCRIPT_DIR/../deploy/k8s/01-secrets" && pwd)"
NAMESPACE="${CENOTOO_NAMESPACE:-cenotoo}"

info()  { printf '\033[1;34m[INFO]\033[0m  %s\n' "$*"; }
ok()    { printf '\033[1;32m[OK]\033[0m    %s\n' "$*"; }
warn()  { printf '\033[1;33m[WARN]\033[0m  %s\n' "$*"; }

b64() { printf '%s' "$1" | base64 -w0; }
rand() { openssl rand -hex 32; }

JWT_SECRET="${CENOTOO_JWT_SECRET:-}"
API_KEY_SECRET="${CENOTOO_API_KEY_SECRET:-}"
CASSANDRA_USERNAME="${CENOTOO_CASSANDRA_USERNAME:-cassandra}"
CASSANDRA_PASSWORD="${CENOTOO_CASSANDRA_PASSWORD:-}"
POSTGRES_USERNAME="${CENOTOO_POSTGRES_USERNAME:-cenotoo}"
POSTGRES_PASSWORD="${CENOTOO_POSTGRES_PASSWORD:-}"
POSTGRES_DATABASE="${CENOTOO_POSTGRES_DATABASE:-cenotoo}"

echo ""
info "Configure secrets (press Enter to autogenerate, or type a value)"
echo ""

if [ -z "$JWT_SECRET" ]; then
    printf "  JWT secret [autogenerate]: "
    read -rs _in; echo ""
    JWT_SECRET="${_in:-$(rand)}"
    [ -z "$_in" ] && ok "JWT secret: autogenerated" || ok "JWT secret: set"
else
    ok "JWT secret: using \$CENOTOO_JWT_SECRET"
fi

if [ -z "$API_KEY_SECRET" ]; then
    printf "  API key secret [autogenerate]: "
    read -rs _in; echo ""
    API_KEY_SECRET="${_in:-$(rand)}"
    [ -z "$_in" ] && ok "API key secret: autogenerated" || ok "API key secret: set"
else
    ok "API key secret: using \$CENOTOO_API_KEY_SECRET"
fi

if [ -z "$CASSANDRA_PASSWORD" ]; then
    printf "  Cassandra password [autogenerate]: "
    read -rs _in; echo ""
    CASSANDRA_PASSWORD="${_in:-$(rand)}"
    [ -z "$_in" ] && ok "Cassandra password: autogenerated" || ok "Cassandra password: set"
else
    ok "Cassandra password: using \$CENOTOO_CASSANDRA_PASSWORD"
fi

if [ -z "$POSTGRES_PASSWORD" ]; then
    printf "  PostgreSQL password [autogenerate]: "
    read -rs _in; echo ""
    POSTGRES_PASSWORD="${_in:-$(rand)}"
    [ -z "$_in" ] && ok "PostgreSQL password: autogenerated" || ok "PostgreSQL password: set"
else
    ok "PostgreSQL password: using \$CENOTOO_POSTGRES_PASSWORD"
fi
echo ""

info "Generating API secrets ..."
cat > "$SECRETS_DIR/api-secrets.yaml" <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: cenotoo-api-secrets
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: cenotoo
type: Opaque
data:
  jwt-secret-key: $(b64 "$JWT_SECRET")
  api-key-secret: $(b64 "$API_KEY_SECRET")
EOF
ok "Generated $SECRETS_DIR/api-secrets.yaml"

info "Generating Cassandra superuser secret ..."
cat > "$SECRETS_DIR/cassandra-superuser.yaml" <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: cenotoo-cassandra-superuser
  labels:
    app.kubernetes.io/part-of: cenotoo
type: Opaque
data:
  username: $(b64 "$CASSANDRA_USERNAME")
  password: $(b64 "$CASSANDRA_PASSWORD")
EOF
ok "Generated $SECRETS_DIR/cassandra-superuser.yaml"

info "Generating PostgreSQL credentials secret ..."
cat > "$SECRETS_DIR/postgres-credentials.yaml" <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: cenotoo-postgres-credentials
  labels:
    app.kubernetes.io/component: postgres
    app.kubernetes.io/part-of: cenotoo
type: Opaque
data:
  username: $(b64 "$POSTGRES_USERNAME")
  password: $(b64 "$POSTGRES_PASSWORD")
  database: $(b64 "$POSTGRES_DATABASE")
EOF
ok "Generated $SECRETS_DIR/postgres-credentials.yaml"

echo ""
ok "Secrets configured"
info "Apply with: kubectl apply -f $SECRETS_DIR/ -n $NAMESPACE"
info "Or run: ./scripts/07-deploy-cenotoo.sh && ./scripts/24-deploy-postgres.sh"
