apiVersion: v2
name: cenotoo
description: Cenotoo distributed data streaming infrastructure
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kafka
  - cassandra
  - flink
  - streaming
